<?php
/**
 * migrar_dados_online.php
 * -----------------------------------------------------------------------------
 * Sobe este arquivo na raiz do sistema (ao lado de db_connection.php) no
 * servidor ONLINE e acesse pela URL com o parametro de confirmacao:
 *
 *     https://SEU-DOMINIO/migrar_dados_online.php?confirmar=SIM
 *
 * O que ele faz:
 *   - Usa o db_connection.php do proprio servidor (credenciais online).
 *   - Insere os dados preservando os IDs originais (mantem as referencias).
 *   - PULA qualquer tabela que JA tenha registros (seguro rodar de novo).
 *   - Insere apenas colunas que existem na tabela de destino (tolera pequenas
 *     diferencas de schema).
 *   - Tudo dentro de uma transacao: se algo falhar, nada e gravado.
 *
 * IMPORTANTE: APAGUE este arquivo do servidor depois de usar.
 * -----------------------------------------------------------------------------
 */

header('Content-Type: text/plain; charset=utf-8');

if (($_GET['confirmar'] ?? '') !== 'SIM') {
    http_response_code(400);
    exit("Confirmacao necessaria. Acesse com ?confirmar=SIM na URL para executar.\n");
}

require_once __DIR__ . '/db_connection.php'; // $pdo do servidor ONLINE

/** Dados exportados do banco local: */
$DADOS = array (
  'usuarios' => 
  array (
    'columns' => 
    array (
      0 => 'id',
      1 => 'email',
      2 => 'senha_hash',
      3 => 'criado_em',
    ),
    'rows' => 
    array (
      0 => 
      array (
        'id' => 1,
        'email' => 'admin',
        'senha_hash' => '$2y$12$JmnoDCKqr9K4tGJdOvWtVu816ONVe3nJSOqVOxIK6eAFkDbD7cmK6',
        'criado_em' => '2026-06-23 16:33:56',
      ),
    ),
  ),
  'clientes' => 
  array (
    'columns' => 
    array (
      0 => 'id',
      1 => 'nome',
      2 => 'email',
      3 => 'telefone',
      4 => 'tipo_pessoa',
      5 => 'documento_principal',
      6 => 'documento_secundario',
      7 => 'cpf',
      8 => 'cnpj',
      9 => 'documento_socio',
      10 => 'empresa',
      11 => 'endereco',
      12 => 'cep',
      13 => 'logradouro',
      14 => 'numero',
      15 => 'complemento',
      16 => 'bairro',
      17 => 'cidade',
      18 => 'estado',
      19 => 'data_cadastro',
      20 => 'banco',
      21 => 'agencia',
      22 => 'conta',
      23 => 'tipo_conta',
      24 => 'chave_pix',
      25 => 'casado',
      26 => 'regime_casamento',
      27 => 'conjuge_nome',
      28 => 'conjuge_cpf',
      29 => 'conjuge_rg',
      30 => 'conjuge_nacionalidade',
      31 => 'conjuge_profissao',
      32 => 'conta_banco',
      33 => 'conta_agencia',
      34 => 'conta_numero',
      35 => 'conta_pix',
      36 => 'conta_tipo',
      37 => 'conta_titular',
      38 => 'conta_documento',
      39 => 'whatsapp',
      40 => 'anotacoes',
      41 => 'conta_pix_tipo',
      42 => 'porte',
      43 => 'representante_nome',
      44 => 'representante_cpf',
      45 => 'representante_rg',
      46 => 'representante_estado_civil',
      47 => 'representante_profissao',
      48 => 'representante_nacionalidade',
      49 => 'representante_endereco',
    ),
    'rows' => 
    array (
      0 => 
      array (
        'id' => 1,
        'nome' => 'DURAMAIS METALIZACAO LTDA',
        'email' => NULL,
        'telefone' => NULL,
        'tipo_pessoa' => 'JURIDICA',
        'documento_principal' => NULL,
        'documento_secundario' => NULL,
        'cpf' => NULL,
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => 'DURAMAIS METALIZACAO LTDA',
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2025-12-31 21:00:00',
        'banco' => NULL,
        'agencia' => NULL,
        'conta' => NULL,
        'tipo_conta' => NULL,
        'chave_pix' => NULL,
        'casado' => 0,
        'regime_casamento' => NULL,
        'conjuge_nome' => NULL,
        'conjuge_cpf' => NULL,
        'conjuge_rg' => NULL,
        'conjuge_nacionalidade' => NULL,
        'conjuge_profissao' => NULL,
        'conta_banco' => NULL,
        'conta_agencia' => NULL,
        'conta_numero' => NULL,
        'conta_pix' => NULL,
        'conta_tipo' => NULL,
        'conta_titular' => NULL,
        'conta_documento' => NULL,
        'whatsapp' => NULL,
        'anotacoes' => NULL,
        'conta_pix_tipo' => NULL,
        'porte' => NULL,
        'representante_nome' => NULL,
        'representante_cpf' => NULL,
        'representante_rg' => NULL,
        'representante_estado_civil' => NULL,
        'representante_profissao' => NULL,
        'representante_nacionalidade' => 'brasileiro(a)',
        'representante_endereco' => NULL,
      ),
      1 => 
      array (
        'id' => 2,
        'nome' => 'J. R. RAPHAEL ENGENHARIA LTDA',
        'email' => NULL,
        'telefone' => NULL,
        'tipo_pessoa' => 'JURIDICA',
        'documento_principal' => NULL,
        'documento_secundario' => NULL,
        'cpf' => NULL,
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => 'J. R. RAPHAEL ENGENHARIA LTDA',
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2025-12-31 21:00:00',
        'banco' => NULL,
        'agencia' => NULL,
        'conta' => NULL,
        'tipo_conta' => NULL,
        'chave_pix' => NULL,
        'casado' => 0,
        'regime_casamento' => NULL,
        'conjuge_nome' => NULL,
        'conjuge_cpf' => NULL,
        'conjuge_rg' => NULL,
        'conjuge_nacionalidade' => NULL,
        'conjuge_profissao' => NULL,
        'conta_banco' => NULL,
        'conta_agencia' => NULL,
        'conta_numero' => NULL,
        'conta_pix' => NULL,
        'conta_tipo' => NULL,
        'conta_titular' => NULL,
        'conta_documento' => NULL,
        'whatsapp' => NULL,
        'anotacoes' => NULL,
        'conta_pix_tipo' => NULL,
        'porte' => NULL,
        'representante_nome' => NULL,
        'representante_cpf' => NULL,
        'representante_rg' => NULL,
        'representante_estado_civil' => NULL,
        'representante_profissao' => NULL,
        'representante_nacionalidade' => 'brasileiro(a)',
        'representante_endereco' => NULL,
      ),
      2 => 
      array (
        'id' => 3,
        'nome' => 'COPERTEC EQUIPAMENTOS INDUSTRIAIS LTDA ME',
        'email' => NULL,
        'telefone' => NULL,
        'tipo_pessoa' => 'JURIDICA',
        'documento_principal' => NULL,
        'documento_secundario' => NULL,
        'cpf' => NULL,
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => 'COPERTEC EQUIPAMENTOS INDUSTRIAIS LTDA ME',
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2025-12-31 21:00:00',
        'banco' => NULL,
        'agencia' => NULL,
        'conta' => NULL,
        'tipo_conta' => NULL,
        'chave_pix' => NULL,
        'casado' => 0,
        'regime_casamento' => NULL,
        'conjuge_nome' => NULL,
        'conjuge_cpf' => NULL,
        'conjuge_rg' => NULL,
        'conjuge_nacionalidade' => NULL,
        'conjuge_profissao' => NULL,
        'conta_banco' => NULL,
        'conta_agencia' => NULL,
        'conta_numero' => NULL,
        'conta_pix' => NULL,
        'conta_tipo' => NULL,
        'conta_titular' => NULL,
        'conta_documento' => NULL,
        'whatsapp' => NULL,
        'anotacoes' => NULL,
        'conta_pix_tipo' => NULL,
        'porte' => NULL,
        'representante_nome' => NULL,
        'representante_cpf' => NULL,
        'representante_rg' => NULL,
        'representante_estado_civil' => NULL,
        'representante_profissao' => NULL,
        'representante_nacionalidade' => 'brasileiro(a)',
        'representante_endereco' => NULL,
      ),
      3 => 
      array (
        'id' => 4,
        'nome' => 'RAVMAQ COMERCIAL LTDA',
        'email' => NULL,
        'telefone' => NULL,
        'tipo_pessoa' => 'JURIDICA',
        'documento_principal' => NULL,
        'documento_secundario' => NULL,
        'cpf' => NULL,
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => NULL,
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2026-07-08 10:32:13',
        'banco' => NULL,
        'agencia' => NULL,
        'conta' => NULL,
        'tipo_conta' => NULL,
        'chave_pix' => NULL,
        'casado' => 0,
        'regime_casamento' => NULL,
        'conjuge_nome' => NULL,
        'conjuge_cpf' => NULL,
        'conjuge_rg' => NULL,
        'conjuge_nacionalidade' => NULL,
        'conjuge_profissao' => NULL,
        'conta_banco' => NULL,
        'conta_agencia' => NULL,
        'conta_numero' => NULL,
        'conta_pix' => NULL,
        'conta_tipo' => NULL,
        'conta_titular' => NULL,
        'conta_documento' => NULL,
        'whatsapp' => NULL,
        'anotacoes' => NULL,
        'conta_pix_tipo' => NULL,
        'porte' => NULL,
        'representante_nome' => NULL,
        'representante_cpf' => NULL,
        'representante_rg' => NULL,
        'representante_estado_civil' => NULL,
        'representante_profissao' => NULL,
        'representante_nacionalidade' => 'brasileiro(a)',
        'representante_endereco' => NULL,
      ),
    ),
  ),
  'sacados' => 
  array (
    'columns' => 
    array (
      0 => 'id',
      1 => 'nome',
      2 => 'email',
      3 => 'telefone',
      4 => 'tipo_pessoa',
      5 => 'documento_principal',
      6 => 'documento_secundario',
      7 => 'cpf',
      8 => 'cnpj',
      9 => 'documento_socio',
      10 => 'empresa',
      11 => 'endereco',
      12 => 'cep',
      13 => 'logradouro',
      14 => 'numero',
      15 => 'complemento',
      16 => 'bairro',
      17 => 'cidade',
      18 => 'estado',
      19 => 'data_cadastro',
    ),
    'rows' => 
    array (
      0 => 
      array (
        'id' => 1,
        'nome' => 'MMV EQUIPAMENTOS INDUSTRIAIS LTDA',
        'email' => 'mmvac@mmvequipamentos.com.br',
        'telefone' => '(19) 3413-5340',
        'tipo_pessoa' => 'JURIDICA',
        'documento_principal' => '05270009000136',
        'documento_secundario' => NULL,
        'cpf' => NULL,
        'cnpj' => '05270009000136',
        'documento_socio' => NULL,
        'empresa' => 'MMV EQUIPAMENTOS INDUSTRIAIS LTDA',
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2025-12-31 21:00:00',
      ),
      1 => 
      array (
        'id' => 2,
        'nome' => 'ALESANDRO DA ROCHA',
        'email' => 'alesandro@gmail.com',
        'telefone' => '(19) 99880-5212',
        'tipo_pessoa' => 'FISICA',
        'documento_principal' => '28816651873',
        'documento_secundario' => NULL,
        'cpf' => '28816651873',
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => NULL,
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2025-12-31 21:00:00',
      ),
      2 => 
      array (
        'id' => 3,
        'nome' => 'ANA CATARINA SPEGIORIN FORASTIERI',
        'email' => NULL,
        'telefone' => '(19) 99738-7008',
        'tipo_pessoa' => 'FISICA',
        'documento_principal' => '26792979899',
        'documento_secundario' => NULL,
        'cpf' => '26792979899',
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => NULL,
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2025-12-31 21:00:00',
      ),
      3 => 
      array (
        'id' => 4,
        'nome' => 'ANDERSON LUCIANO CAMPION',
        'email' => 'andersonlucianocampion@hotmail.com',
        'telefone' => '(19) 99984-5342',
        'tipo_pessoa' => 'FISICA',
        'documento_principal' => '23411615885',
        'documento_secundario' => NULL,
        'cpf' => '23411615885',
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => NULL,
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2026-04-23 00:00:00',
      ),
      4 => 
      array (
        'id' => 5,
        'nome' => 'IUDICE ODONTOLOGIA AVANCADA LTDA',
        'email' => NULL,
        'telefone' => '(15) 90127-9119',
        'tipo_pessoa' => 'JURIDICA',
        'documento_principal' => '35160323000127',
        'documento_secundario' => NULL,
        'cpf' => NULL,
        'cnpj' => '35160323000127',
        'documento_socio' => NULL,
        'empresa' => 'IUDICE ODONTOLOGIA AVANCADA LTDA',
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2026-04-14 00:00:00',
      ),
      5 => 
      array (
        'id' => 6,
        'nome' => 'R&G COMÉRCIO DE ARTIGOS INFANTIS LTDA',
        'email' => NULL,
        'telefone' => '(19) 96160-5564',
        'tipo_pessoa' => 'JURIDICA',
        'documento_principal' => '43559357000126',
        'documento_secundario' => NULL,
        'cpf' => NULL,
        'cnpj' => '43559357000126',
        'documento_socio' => NULL,
        'empresa' => 'R&G COMÉRCIO DE ARTIGOS INFANTIS LTDA',
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2026-04-28 00:00:00',
      ),
      6 => 
      array (
        'id' => 7,
        'nome' => 'Cristian Weiser',
        'email' => 'cris@cris.com',
        'telefone' => '(19) 99898-9999',
        'tipo_pessoa' => 'FISICA',
        'documento_principal' => '22723140022',
        'documento_secundario' => NULL,
        'cpf' => '22723140022',
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => NULL,
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2026-01-01 00:00:00',
      ),
      7 => 
      array (
        'id' => 8,
        'nome' => 'LA SOARES DE CAMPO',
        'email' => NULL,
        'telefone' => NULL,
        'tipo_pessoa' => 'JURIDICA',
        'documento_principal' => NULL,
        'documento_secundario' => NULL,
        'cpf' => NULL,
        'cnpj' => NULL,
        'documento_socio' => NULL,
        'empresa' => NULL,
        'endereco' => NULL,
        'cep' => NULL,
        'logradouro' => NULL,
        'numero' => NULL,
        'complemento' => NULL,
        'bairro' => NULL,
        'cidade' => NULL,
        'estado' => NULL,
        'data_cadastro' => '2026-07-08 10:32:13',
      ),
    ),
  ),
  'leads' => 
  array (
    'columns' => 
    array (
      0 => 'id',
      1 => 'empresa',
      2 => 'nome_contato',
      3 => 'telefone',
      4 => 'origem',
      5 => 'estagio',
      6 => 'responsavel_id',
      7 => 'cliente_id',
      8 => 'data_visita_agendada',
      9 => 'motivo_perda',
      10 => 'observacoes',
      11 => 'data_cadastro',
      12 => 'data_atualizacao',
    ),
    'rows' => 
    array (
      0 => 
      array (
        'id' => 1,
        'empresa' => 'X',
        'nome_contato' => 'XX',
        'telefone' => '',
        'origem' => 'receptivo',
        'estagio' => 'visita_agendada',
        'responsavel_id' => NULL,
        'cliente_id' => NULL,
        'data_visita_agendada' => NULL,
        'motivo_perda' => NULL,
        'observacoes' => '',
        'data_cadastro' => '2026-06-25 16:56:36',
        'data_atualizacao' => '2026-06-25 16:56:49',
      ),
    ),
  ),
  'leads_historico' => 
  array (
    'columns' => 
    array (
      0 => 'id',
      1 => 'lead_id',
      2 => 'estagio_de',
      3 => 'estagio_para',
      4 => 'usuario_id',
      5 => 'observacao',
      6 => 'data_evento',
    ),
    'rows' => 
    array (
      0 => 
      array (
        'id' => 1,
        'lead_id' => 1,
        'estagio_de' => NULL,
        'estagio_para' => 'novo',
        'usuario_id' => 1,
        'observacao' => 'Lead criado',
        'data_evento' => '2026-06-25 16:56:36',
      ),
      1 => 
      array (
        'id' => 2,
        'lead_id' => 1,
        'estagio_de' => 'novo',
        'estagio_para' => 'visita_agendada',
        'usuario_id' => 1,
        'observacao' => NULL,
        'data_evento' => '2026-06-25 16:56:48',
      ),
      2 => 
      array (
        'id' => 3,
        'lead_id' => 1,
        'estagio_de' => 'visita_agendada',
        'estagio_para' => 'visita_feita',
        'usuario_id' => 1,
        'observacao' => NULL,
        'data_evento' => '2026-06-25 16:56:49',
      ),
      3 => 
      array (
        'id' => 4,
        'lead_id' => 1,
        'estagio_de' => 'visita_feita',
        'estagio_para' => 'visita_agendada',
        'usuario_id' => 1,
        'observacao' => NULL,
        'data_evento' => '2026-06-25 16:56:49',
      ),
    ),
  ),
  'operacoes' => 
  array (
    'columns' => 
    array (
      0 => 'id',
      1 => 'cedente_id',
      2 => 'taxa_mensal',
      3 => 'data_operacao',
      4 => 'data_base_calculo',
      5 => 'tipo_pagamento',
      6 => 'tipo_operacao',
      7 => 'tem_garantia',
      8 => 'descricao_garantia',
      9 => 'total_original_calc',
      10 => 'total_presente_calc',
      11 => 'iof_total_calc',
      12 => 'total_liquido_pago_calc',
      13 => 'incorre_custo_iof',
      14 => 'cobrar_iof_cliente',
      15 => 'total_lucro_liquido_calc',
      16 => 'media_dias_pond_calc',
      17 => 'notas',
      18 => 'valor_total_compensacao',
      19 => 'natureza',
      20 => 'valor_principal',
      21 => 'valor_total_devido',
      22 => 'taxa_juros_mensal',
      23 => 'taxa_juros_anual',
      24 => 'cet_mensal',
      25 => 'num_parcelas',
      26 => 'valor_parcela',
      27 => 'data_primeiro_vencimento',
      28 => 'periodicidade',
      29 => 'taxa_desagio_mensal',
      30 => 'status_contrato',
    ),
    'rows' => 
    array (
      0 => 
      array (
        'id' => 1,
        'cedente_id' => 1,
        'taxa_mensal' => '0.0550',
        'data_operacao' => '2026-03-19 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'antecipacao',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => '23924.32',
        'total_presente_calc' => NULL,
        'iof_total_calc' => NULL,
        'total_liquido_pago_calc' => '22515.77',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 1,
        'total_lucro_liquido_calc' => '1408.55',
        'media_dias_pond_calc' => NULL,
        'notas' => NULL,
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      1 => 
      array (
        'id' => 3,
        'cedente_id' => 2,
        'taxa_mensal' => '0.0550',
        'data_operacao' => '2026-03-31 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'antecipacao',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => '35000.00',
        'total_presente_calc' => NULL,
        'iof_total_calc' => NULL,
        'total_liquido_pago_calc' => '32939.37',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 1,
        'total_lucro_liquido_calc' => '2060.63',
        'media_dias_pond_calc' => NULL,
        'notas' => NULL,
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      2 => 
      array (
        'id' => 4,
        'cedente_id' => 3,
        'taxa_mensal' => '0.0550',
        'data_operacao' => '2026-04-08 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'antecipacao',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => '6220.00',
        'total_presente_calc' => NULL,
        'iof_total_calc' => NULL,
        'total_liquido_pago_calc' => '5927.39',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 1,
        'total_lucro_liquido_calc' => '292.61',
        'media_dias_pond_calc' => NULL,
        'notas' => NULL,
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      3 => 
      array (
        'id' => 8,
        'cedente_id' => NULL,
        'taxa_mensal' => '0.0550',
        'data_operacao' => '2026-02-13 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'emprestimo',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => '3060.03',
        'total_presente_calc' => NULL,
        'iof_total_calc' => NULL,
        'total_liquido_pago_calc' => '2818.28',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 1,
        'total_lucro_liquido_calc' => '241.75',
        'media_dias_pond_calc' => NULL,
        'notas' => NULL,
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      4 => 
      array (
        'id' => 9,
        'cedente_id' => NULL,
        'taxa_mensal' => '0.0550',
        'data_operacao' => '2026-02-06 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'emprestimo',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => '3000.00',
        'total_presente_calc' => NULL,
        'iof_total_calc' => NULL,
        'total_liquido_pago_calc' => '2722.99',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 1,
        'total_lucro_liquido_calc' => '277.01',
        'media_dias_pond_calc' => NULL,
        'notas' => NULL,
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      5 => 
      array (
        'id' => 10,
        'cedente_id' => NULL,
        'taxa_mensal' => '0.0550',
        'data_operacao' => '2026-03-31 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'emprestimo',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => '1500.00',
        'total_presente_calc' => NULL,
        'iof_total_calc' => NULL,
        'total_liquido_pago_calc' => '1444.82',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 1,
        'total_lucro_liquido_calc' => '55.18',
        'media_dias_pond_calc' => NULL,
        'notas' => NULL,
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      6 => 
      array (
        'id' => 11,
        'cedente_id' => NULL,
        'taxa_mensal' => '0.0550',
        'data_operacao' => '2026-04-14 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'emprestimo',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => NULL,
        'total_presente_calc' => NULL,
        'iof_total_calc' => NULL,
        'total_liquido_pago_calc' => '18000.00',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 0,
        'total_lucro_liquido_calc' => NULL,
        'media_dias_pond_calc' => NULL,
        'notas' => NULL,
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      7 => 
      array (
        'id' => 12,
        'cedente_id' => NULL,
        'taxa_mensal' => '0.0550',
        'data_operacao' => '2026-04-23 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'emprestimo',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => NULL,
        'total_presente_calc' => NULL,
        'iof_total_calc' => NULL,
        'total_liquido_pago_calc' => '10810.00',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 0,
        'total_lucro_liquido_calc' => NULL,
        'media_dias_pond_calc' => NULL,
        'notas' => NULL,
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      8 => 
      array (
        'id' => 13,
        'cedente_id' => NULL,
        'taxa_mensal' => '0.0660',
        'data_operacao' => '2026-04-28 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'emprestimo',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => '7998.00',
        'total_presente_calc' => NULL,
        'iof_total_calc' => '30.39',
        'total_liquido_pago_calc' => '6141.18',
        'incorre_custo_iof' => 0,
        'cobrar_iof_cliente' => 0,
        'total_lucro_liquido_calc' => '1856.82',
        'media_dias_pond_calc' => NULL,
        'notas' => 'compra de coleção infantil para a loja',
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
      9 => 
      array (
        'id' => 14,
        'cedente_id' => 4,
        'taxa_mensal' => '0.0500',
        'data_operacao' => '2026-06-25 00:00:00',
        'data_base_calculo' => NULL,
        'tipo_pagamento' => 'direto',
        'tipo_operacao' => 'antecipacao',
        'tem_garantia' => 0,
        'descricao_garantia' => NULL,
        'total_original_calc' => '58250.00',
        'total_presente_calc' => '50971.88',
        'iof_total_calc' => '221.35',
        'total_liquido_pago_calc' => '50750.53',
        'incorre_custo_iof' => 1,
        'cobrar_iof_cliente' => 1,
        'total_lucro_liquido_calc' => '7278.12',
        'media_dias_pond_calc' => 84,
        'notas' => 'INDICAÇÃO MAGNANI',
        'valor_total_compensacao' => '0.00',
        'natureza' => 'DESCONTO',
        'valor_principal' => NULL,
        'valor_total_devido' => NULL,
        'taxa_juros_mensal' => NULL,
        'taxa_juros_anual' => NULL,
        'cet_mensal' => NULL,
        'num_parcelas' => NULL,
        'valor_parcela' => NULL,
        'data_primeiro_vencimento' => NULL,
        'periodicidade' => 'mensais',
        'taxa_desagio_mensal' => NULL,
        'status_contrato' => 'pendente',
      ),
    ),
  ),
  'recebiveis' => 
  array (
    'columns' => 
    array (
      0 => 'id',
      1 => 'operacao_id',
      2 => 'sacado_id',
      3 => 'tipo_recebivel',
      4 => 'valor_original',
      5 => 'valor_recebido',
      6 => 'data_vencimento',
      7 => 'valor_presente_calc',
      8 => 'iof_calc',
      9 => 'valor_liquido_calc',
      10 => 'dias_prazo_calc',
      11 => 'status',
      12 => 'data_recebimento',
      13 => 'obs_problema',
    ),
    'rows' => 
    array (
      0 => 
      array (
        'id' => 1,
        'operacao_id' => 1,
        'sacado_id' => 1,
        'tipo_recebivel' => 'duplicata',
        'valor_original' => '23924.32',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-04-22',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Recebido',
        'data_recebimento' => '2026-04-22 00:00:00',
        'obs_problema' => NULL,
      ),
      1 => 
      array (
        'id' => 4,
        'operacao_id' => 3,
        'sacado_id' => 1,
        'tipo_recebivel' => 'duplicata',
        'valor_original' => '35000.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-05-04',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      2 => 
      array (
        'id' => 7,
        'operacao_id' => 4,
        'sacado_id' => 1,
        'tipo_recebivel' => 'duplicata',
        'valor_original' => '2700.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-05-05',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      3 => 
      array (
        'id' => 8,
        'operacao_id' => 4,
        'sacado_id' => 1,
        'tipo_recebivel' => 'duplicata',
        'valor_original' => '3520.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-05-05',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      4 => 
      array (
        'id' => 24,
        'operacao_id' => 8,
        'sacado_id' => 2,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '1020.01',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-03-01',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Recebido',
        'data_recebimento' => '2026-03-01 00:00:00',
        'obs_problema' => NULL,
      ),
      5 => 
      array (
        'id' => 25,
        'operacao_id' => 8,
        'sacado_id' => 2,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '1020.01',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-04-01',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      6 => 
      array (
        'id' => 26,
        'operacao_id' => 8,
        'sacado_id' => 2,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '1020.01',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-05-01',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      7 => 
      array (
        'id' => 34,
        'operacao_id' => 9,
        'sacado_id' => 2,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '1500.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-03-17',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Recebido',
        'data_recebimento' => '2026-03-17 00:00:00',
        'obs_problema' => NULL,
      ),
      8 => 
      array (
        'id' => 35,
        'operacao_id' => 9,
        'sacado_id' => 2,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '1500.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-04-17',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      9 => 
      array (
        'id' => 44,
        'operacao_id' => 10,
        'sacado_id' => 3,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '1500.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-04-21',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Recebido',
        'data_recebimento' => '2026-04-21 00:00:00',
        'obs_problema' => NULL,
      ),
      10 => 
      array (
        'id' => 66,
        'operacao_id' => 13,
        'sacado_id' => 6,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '7998.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-08-30',
        'valor_presente_calc' => NULL,
        'iof_calc' => NULL,
        'valor_liquido_calc' => NULL,
        'dias_prazo_calc' => NULL,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      11 => 
      array (
        'id' => 67,
        'operacao_id' => 14,
        'sacado_id' => 8,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '11650.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-07-17',
        'valor_presente_calc' => '11240.54',
        'iof_calc' => '44.27',
        'valor_liquido_calc' => '11196.27',
        'dias_prazo_calc' => 22,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      12 => 
      array (
        'id' => 68,
        'operacao_id' => 14,
        'sacado_id' => 8,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '11650.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-08-17',
        'valor_presente_calc' => '10687.88',
        'iof_calc' => '44.27',
        'valor_liquido_calc' => '10643.61',
        'dias_prazo_calc' => 53,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      13 => 
      array (
        'id' => 69,
        'operacao_id' => 14,
        'sacado_id' => 8,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '11650.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-09-17',
        'valor_presente_calc' => '10162.39',
        'iof_calc' => '44.27',
        'valor_liquido_calc' => '10118.12',
        'dias_prazo_calc' => 84,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      14 => 
      array (
        'id' => 70,
        'operacao_id' => 14,
        'sacado_id' => 8,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '11650.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-10-17',
        'valor_presente_calc' => '9678.47',
        'iof_calc' => '44.27',
        'valor_liquido_calc' => '9634.20',
        'dias_prazo_calc' => 114,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
      15 => 
      array (
        'id' => 71,
        'operacao_id' => 14,
        'sacado_id' => 8,
        'tipo_recebivel' => 'fatura',
        'valor_original' => '11650.00',
        'valor_recebido' => NULL,
        'data_vencimento' => '2026-11-17',
        'valor_presente_calc' => '9202.61',
        'iof_calc' => '44.27',
        'valor_liquido_calc' => '9158.34',
        'dias_prazo_calc' => 145,
        'status' => 'Em Aberto',
        'data_recebimento' => NULL,
        'obs_problema' => NULL,
      ),
    ),
  ),
);

// ----------------------------------------------------------------------------
$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
$relatorio = [];

try {
    $pdo->exec('SET FOREIGN_KEY_CHECKS = 0');
    $pdo->beginTransaction();

    foreach ($DADOS as $tabela => $info) {
        // Ja tem dados? Pula por seguranca.
        $existentes = (int) $pdo->query("SELECT COUNT(*) FROM `$tabela`")->fetchColumn();
        if ($existentes > 0) {
            $relatorio[] = sprintf('PULADO  %-18s (ja possui %d registros)', $tabela, $existentes);
            continue;
        }

        // Colunas reais da tabela de destino (intersecao com as exportadas)
        $colsDestino = [];
        foreach ($pdo->query("DESCRIBE `$tabela`") as $c) { $colsDestino[$c['Field']] = true; }
        $cols = array_values(array_filter($info['columns'], fn($c) => isset($colsDestino[$c])));

        if (empty($cols)) {
            $relatorio[] = sprintf('ERRO    %-18s (nenhuma coluna compativel)', $tabela);
            continue;
        }

        $lista       = '`' . implode('`, `', $cols) . '`';
        $placeholders = implode(', ', array_fill(0, count($cols), '?'));
        $stmt = $pdo->prepare("INSERT INTO `$tabela` ($lista) VALUES ($placeholders)");

        $n = 0;
        foreach ($info['rows'] as $row) {
            $valores = [];
            foreach ($cols as $c) { $valores[] = $row[$c] ?? null; }
            $stmt->execute($valores);
            $n++;
        }
        $relatorio[] = sprintf('OK      %-18s %d registros inseridos', $tabela, $n);
    }

    $pdo->commit();
    $pdo->exec('SET FOREIGN_KEY_CHECKS = 1');

    echo "MIGRACAO CONCLUIDA COM SUCESSO\n";
    echo str_repeat('-', 50) . "\n";
    echo implode("\n", $relatorio) . "\n";
    echo str_repeat('-', 50) . "\n";
    echo "APAGUE este arquivo do servidor agora.\n";

} catch (Throwable $e) {
    if ($pdo->inTransaction()) { $pdo->rollBack(); }
    $pdo->exec('SET FOREIGN_KEY_CHECKS = 1');
    http_response_code(500);
    echo "FALHA NA MIGRACAO - nada foi gravado (rollback).\n";
    echo 'Erro: ' . $e->getMessage() . "\n";
    if ($relatorio) { echo "\nProgresso antes da falha:\n" . implode("\n", $relatorio) . "\n"; }
}